mutation {
  login(username: "user", password: "123456") {
    id
    username
    email
    token
    createdAt
  }
}

mutation {
  createPost(body: "A post for subscriber 3") {
    id
    body
    username
    createdAt
    comments {
      id
      username
      body
      createdAt
    }
    likes {
      id
      username
      createdAt
    }
  }
}

subscription {
  newPost {
    id
    body
    username
    createdAt
    comments {
      id
      username
      body
      createdAt
    }
    likes {
      id
      username
      createdAt
    }
  }
}

{
  getPosts {
    id
    body
    username
    createdAt
    comments {
      id
      username
      body
      createdAt
    }
    likes {
      id
      username
      createdAt
    }
    commentCount
    likeCount
  }
}

mutation {
  createComment(postId: "5e5651ea00bcee4b00f149af", body: "Test comments 1") {
    id
    body
    username
    createdAt
    comments {
      id
      username
      body
      createdAt
    }
    likes {
      id
      username
      createdAt
    }
    commentCount
    likeCount
  }
}

mutation {
  deleteComment(
    postId: "5e5651ea00bcee4b00f149af"
    commentId: "5e574a98c5566b12e300eaea"
  ) {
    id
    body
    username
    createdAt
    comments {
      id
      username
      body
      createdAt
    }
    likes {
      id
      username
      createdAt
    }
    commentCount
    likeCount
  }
}
